// Code generated by hertz generator.

package main

import (
	"time"
	"voacap/biz/dal"

	"github.com/cloudwego/hertz/pkg/app/server"
)

func Init() {
	dal.Init()
}

func main() {
	Init()

	h := server.Default(server.WithHostPorts(":3000"), server.WithExitWaitTime(time.Second))

	register(h)
	h.Spin()
}
