// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	antennas "voacap/internal/voacap/biz/router/antennas"
	link "voacap/internal/voacap/biz/router/link"
	station "voacap/internal/voacap/biz/router/station"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	station.Register(r)

	antennas.Register(r)

	link.Register(r)
}
