// Code generated by hertz generator.

package link

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _linksMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _addlinkMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deletelinkbyidMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getlinksMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updatelinkbyidMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _writelink2fileMw() []app.HandlerFunc {
	// your code...
	return nil
}
