// Code generated by hertz generator.

package station

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _stationMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getstationsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _stationsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _addstationMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updatestationbyidMw() []app.HandlerFunc {
	// your code...
	return nil
}
