// Code generated by hertz generator.

package antennas

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getantennasMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _antennasMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _addantennaMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updateantennabyidMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deleteantennabyidMw() []app.HandlerFunc {
	// your code...
	return nil
}
